version: '{build}'
image:
- Visual Studio 2017
# - Visual Studio 2015
platform: x64
environment:
  matrix:
  - PLATFORM: x64
  # - PLATFORM: x86
branches:
  only:
  - feature/netstandard2
build_script:
- cmd: >-
    dotnet restore

    dotnet build --configuration Debug --no-restore

# Running tests will be such that current directory is [...]\dynamic-interop-dll\DynamicInterop.Tests\bin\Debug\netcoreapp2.0, so adapt DynamicInteropTestLibPath
test_script:
- cmd: >-
    set DynamicInteropTestLibPath=..\..\..\..\x64\Debug

    dotnet test DynamicInterop.Tests/DynamicInterop.Tests.csproj
