language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

script:
- dotnet restore
- dotnet build --configuration Release --no-restore
- dotnet pack DynamicInterop/DynamicInterop.csproj --configuration Release --no-build --no-restore --output nupkgs
