language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

script:
- export DynamicInteropTestLibPath='/home/travis/build/screig/dynamic-interop-dll/DynamicInterop.Tests/bin/Release/netcoreapp2.0'

- DYNINTEROP_BIN_DIR='/home/travis/build/screig/dynamic-interop-dll/DynamicInterop/bin/Release/netstandard2.0'
- cd libdlwrap
- make
- cp sample.config $DYNINTEROP_BIN_DIR/DynamicInterop.dll.config
- cp libdlwrap.so  $DYNINTEROP_BIN_DIR/


- dotnet restore
- dotnet build --configuration Release --no-restore
- dotnet test DynamicInterop.Tests/DynamicInterop.Tests.csproj
- dotnet pack DynamicInterop/DynamicInterop.csproj --configuration Release --no-build --no-restore --output nupkgs
