language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

script:
- dotnet restore DynamicInterop_csharp.sln
- dotnet build --configuration Release --no-restore DynamicInterop_csharp.sln

- cd DynamicInterop.Tests
- cd test_native_library
- cmake -H. -Bbuild
- cmake --build build -- -j3
- cd ..
- cd ..

# - DYNINTEROP_BIN_DIR='/home/travis/build/jmp75/dynamic-interop-dll/DynamicInterop/bin/Release/netstandard2.0'
# - cd libdlwrap
# - make
# - cp sample.config $DYNINTEROP_BIN_DIR/DynamicInterop.dll.config
# - cp libdlwrap.so  $DYNINTEROP_BIN_DIR/
# - cd ..

# - export DynamicInteropTestLibPath='/home/travis/build/jmp75/dynamic-interop-dll/DynamicInterop.Tests/test_native_library/build'
# - dotnet test DynamicInterop.Tests/DynamicInterop.Tests.csproj
# - dotnet pack DynamicInterop/DynamicInterop.csproj --configuration Release --no-build --no-restore --output nupkgs
